### ISSUE TITLE
Need help in understanding getTracer() in controllers.go

### ISSUE THREAD

**Issue by vijay-stephen** [ChrisJBurns/jaeger-tracing-go-service#1]
can you please clarify the need of getTracer function in controllers.go ? 

func getTracer(c *gin.Context) oteltrace.Tracer{
	var tracer oteltrace.Tracer
	tracerInterface, ok := c.Get("otel-go-contrib-tracer")
	if ok {
		tracer, ok = tracerInterface.(oteltrace.Tracer)
	}
	return tracer
}

**Comment by ChrisJBurns** [comment]
Hi,

Must have got missed when removing old code. Have removed in the following PR: https://github.com/ChrisJBurns/jaeger-tracing-go-service/pull/3
